trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'Build Angular App'

- task: Maven@3
  inputs:
    mavenPomFile: 'backend/pom.xml'  # Path to your backend's pom.xml
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Build Java Backend'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Angular Build Output'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'angular-dist'
    publishLocation: 'Container'
  displayName: 'Publish Angular Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'backend/target'
    artifactName: 'java-dist'
    publishLocation: 'Container'
  displayName: 'Publish Java Artifacts'
